
export const cars = [
    {
        brand:"Toyota",
        preci:"20",
        description:"Vehiculo bajo",
        fuelConsumption:"1.5L for 200KM",
        location:"55 Fruit St, Boston, MA 02114, Estados Unidos",
        colour:["white"],
        discount:10,
        doors:"2",
        line:"Auris",
        category:"Sedan",
        fuelType:"gasoline",
        typeOfBox:"Handbook",
        licensePlate:"5531 LKC",
        image:"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQWjjlMTibcTWRyZBCpc-4a-Q87TzZ4-f4n3UXvXAh6TLq5Bgi_"
    },
    {
        brand:"Renault",
        preci:"22",
        description:"Vehiculo medio-alto",
        fuelConsumption:"1.5L for 80KM",
        location:"55 Fruit St, Boston, MA 02114, Estados Unidos",
        colour:["red"],
        discount:10,
        doors:"2",
        line:"Duster",
        category:"Pick-Up",
        fuelType:"electric",
        typeOfBox:"automatic",
        licensePlate:"5785 LKC",
        image:"https://content.r9cdn.net/rimg/carimages/generic/02_economy_red.png?height=116"
    },
    {
        brand:"Renault",
        preci:"22",
        description:"Vehiculo Ciudad",
        fuelConsumption:"1.5L for 50KM",
        location:"55 Fruit St, Boston, MA 02114, Estados Unidos",
        colour:["blue"],
        discount:0,
        doors:"4",
        line:"Andar",
        category:"Minivan",
        fuelType:"hybrid",
        typeOfBox:"Handbook",
        licensePlate:"1542 LKC",
        image:"https://content.r9cdn.net/rimg/carimages/generic/01_mini_darkblue.png?height=116"
    },
    {
        brand:"Renault",
        preci:"18",
        description:"Vehiculo Ciudad",
        fuelConsumption:"1.5L for 50KM",
        location:"55 Fruit St, Boston, MA 02114, Estados Unidos",
        colour:["blue"],
        discount:20,
        doors:"5",
        line:"Captur",
        category:"Minivan",
        fuelType:"gas",
        typeOfBox:"semiautomatic",
        licensePlate:"8754 LKC",
        image:"https://content.r9cdn.net/rimg/carimages/generic/02_economy_red.png?height=116"
    },
    {
        brand:"Renault",
        preci:"19",
        description:"Vehiculo Ciudad",
        fuelConsumption:"1.5L for 100KM",
        location:"55 Fruit St, Boston, MA 02114, Estados Unidos",
        colour:["Black","blue"],
        discount:0,
        doors:"4",
        line:"raptor",
        category:"Minivan",
        fuelType:"electric",
        typeOfBox:"automatic",
        licensePlate:"8378 LKC",
        image:"https://content.r9cdn.net/rimg/carimages/generic/01_mini_darkblue.png?height=116"
    },
    {
        brand:"Volkswagen",
        preci:"24",
        description:"Vehiculo todo terreno",
        fuelConsumption:"1.5L for 10KM",
        location:"55 Fruit St, Boston, MA 02114, Estados Unidos",
        colour:["Black","cream"],
        discount:10,
        doors:"5",
        line:"Polo",
        category:"SUV",
        fuelType:"hybrid",
        typeOfBox:"Handbook",
        licensePlate:"8795 LKC",
        image:"https://content.r9cdn.net/rimg/carimages/generic/01_mini_beige.png?height=116"
    },
    {
        brand:"Renault",
        preci:"15",
        description:"Vehiculo medio-alto",
        fuelConsumption:"1.5L for 80KM",
        location:"55 Fruit St, Boston, MA 02114, Estados Unidos",
        colour:["red"],
        discount:0,
        doors:"5",
        line:"Rose",
        category:"Sedan",
        fuelType:"electric",
        typeOfBox:"semiautomatic",
        licensePlate:"1452 LKC",
        image:"https://content.r9cdn.net/rimg/carimages/generic/02_economy_red.png?height=116"
    },
    {
        brand:"Chevrolet",
        preci:"18",
        description:"Vehiculo para ciudad",
        fuelConsumption:"1.5L for 60KM",
        location:"55 Fruit St, Boston, MA 02114, Estados Unidos",
        colour:["Black"],
        discount:0,
        doors:"4",
        line:"Sail",
        category:"Sedan",
        fuelType:"hybrid",
        typeOfBox:"automatic",
        licensePlate:"8752 LKC",
        image:"https://content.r9cdn.net/rimg/carimages/generic/03_standard_black.png?height=116"
    },
    {
        brand:"Renault",
        preci:"26",
        description:"Vehiculo Ciudad",
        fuelConsumption:"1.5L for 50KM",
        location:"55 Fruit St, Boston, MA 02114, Estados Unidos",
        colour:["blue"],
        discount:10,
        doors:"2",
        line:"Renux",
        category:"Minivan",
        fuelType:"gasoline",
        typeOfBox:"semiautomatic",
        licensePlate:"8754 LKC",
        image:"https://content.r9cdn.net/rimg/carimages/generic/01_mini_darkblue.png?height=116"
    },
    {
        brand:"Hyundai",
        preci:"23",
        description:"Vehiculo todo terreno",
        fuelConsumption:"1.5L for 40KM",
        location:"55 Fruit St, Boston, MA 02114, Estados Unidos",
        colour:["Black","white"],
        discount:20,
        doors:"2",
        line:"GRAND",
        category:"Pick-Up",
        fuelType:"gas",
        typeOfBox:"semiautomatic",
        licensePlate:"8754 LKC",
        image:"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQWjjlMTibcTWRyZBCpc-4a-Q87TzZ4-f4n3UXvXAh6TLq5Bgi_"
    },
    {
        brand:"Toyota",
        preci:"20",
        description:"Vehiculo bajo",
        fuelConsumption:"1.5L for 200KM",
        location:"55 Fruit St, Boston, MA 02114, Estados Unidos",
        colour:["white"],
        discount:10,
        doors:"4",
        line:"cool",
        category:"Sedan",
        fuelType:"electric",
        typeOfBox:"Handbook",
        licensePlate:"7854 LKC",
        image:"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQWjjlMTibcTWRyZBCpc-4a-Q87TzZ4-f4n3UXvXAh6TLq5Bgi_"
    },
    {
        brand:"Renault",
        preci:"14",
        description:"Vehiculo medio-alto",
        fuelConsumption:"1.5L for 80KM",
        location:"55 Fruit St, Boston, MA 02114, Estados Unidos",
        colour:["red"],
        discount:5,
        doors:"5",
        line:"Platon",
        category:"Minivan",
        fuelType:"electric",
        typeOfBox:"Handbook",
        licensePlate:"7854 LKC",
        image:"https://content.r9cdn.net/rimg/carimages/generic/02_economy_red.png?height=116"
    },
    {
        brand:"Renault",
        preci:"19",
        description:"Vehiculo Ciudad",
        fuelConsumption:"1.5L for 50KM",
        location:"55 Fruit St, Boston, MA 02114, Estados Unidos",
        colour:["blue"],
        discount:0,
        doors:"5",
        line:"Montero",
        category:"Minivan",
        fuelType:"hybrid",
        typeOfBox:"semiautomatic",
        licensePlate:"7854 LKC",
        image:"https://content.r9cdn.net/rimg/carimages/generic/01_mini_darkblue.png?height=116"
    },
    {
        brand:"Renault",
        preci:"21",
        description:"Vehiculo Ciudad",
        fuelConsumption:"1.5L for 100KM",
        location:"55 Fruit St, Boston, MA 02114, Estados Unidos",
        colour:["Black","blue"],
        discount:10,
        doors:"5",
        line:"Colorado",
        category:"Minivan",
        fuelType:"electric",
        typeOfBox:"semiautomatic",
        licensePlate:"8378 LKC",
        image:"https://content.r9cdn.net/rimg/carimages/generic/01_mini_darkblue.png?height=116"
    },
    {
        brand:"Volkswagen",
        preci:"18",
        description:"Vehiculo todo terreno",
        fuelConsumption:"1.5L for 10KM",
        location:"55 Fruit St, Boston, MA 02114, Estados Unidos",
        colour:["Black","cream"],
        discount:20,
        doors:"4",
        line:"Full",
        category:"SUV",
        fuelType:"gasoline",
        typeOfBox:"Handbook",
        licensePlate:"7854 LKC",
        image:"https://content.r9cdn.net/rimg/carimages/generic/01_mini_beige.png?height=116"
    },
    {
        brand:"Chevrolet",
        preci:"25",
        description:"Vehiculo para ciudad",
        fuelConsumption:"1.5L for 60KM",
        location:"55 Fruit St, Boston, MA 02114, Estados Unidos",
        colour:["Black"],
        discount:5,
        doors:"4",
        line:"Racet",
        category:"Sedan",
        fuelType:"hybrid",
        typeOfBox:"Handbook",
        licensePlate:"8752 LKC",
        image:"https://content.r9cdn.net/rimg/carimages/generic/03_standard_black.png?height=116"
    },
    {
        brand:"Hyundai",
        preci:"17",
        description:"Vehiculo todo terreno",
        fuelConsumption:"1.5L for 40KM",
        location:"55 Fruit St, Boston, MA 02114, Estados Unidos",
        colour:["Black","white"],
        discount:10,
        doors:"4",
        line:"Pocol",
        category:"Pick-Up",
        fuelType:"hybrid",
        typeOfBox:"semiautomatic",
        licensePlate:"7854 LKC",
        image:"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQWjjlMTibcTWRyZBCpc-4a-Q87TzZ4-f4n3UXvXAh6TLq5Bgi_"
    }]